### ISSUE TITLE
Error: the number of characters of the message dont match

### ISSUE THREAD

**Issue by fakereto** [OscarRicoB/P1-encrypted-message-Python#1]
En todos los casos de prueba regresa el mismo error: 
Error: the number of characters of the message dont match

**Comment by OscarRicoB** [comment]
En el mismo ejemplo que ponen en el documento que me pasaste, ponen como valido este ejemplo
11 15 38

CeseAlFuego

CorranACubierto

XXcaaamakkCCessseAAllFueeegooDLLKmmNNN

y con esta es  salida
SI

NO

El cual claramente debe de dar un erro ya que dice que el mensaje es de 38 caracteres, pero si lo pasas por el algoritmo este queda de 22 caracteres, y veo que la mayoría de lo errores van de la mano de ese caso "Error: the number of characters of the message dont match"

cito esta frase contenida en el problema "(Nota: Ninguna instrucción en el libro de instrucciones contiene dos letras iguales seguidas)"

o yo lo sintetice mal?
"Desafortunadamente el transmisor que ocupan para el envío de los mensajes tiene una falla. En lugar de enviar los caracteres una sola vez, esta enviándolos una, dos o hasta tres veces. Por ejemplo, el mensaje anterior pudiera ser enviado así: XXcaaamakkCCessseAAllFueeegooDLLKmmNNN. Esto hace que sea más difícil para los agentes  el encontrar una instrucción. (Nota: Ninguna instrucción en el libro de instrucciones contiene dos letras iguales seguidas)"

y luego mencionan
 
"La primera línea son tres enteros M1, M2 y N. M1 y M2 es el número de caracteres de las dos instrucciones y N es el número de caracteres en el mensaje."
si N es el numero de caracteres en el mensaje, pero el único error que tiene el aparato es que envía duplicados los caracteres en el mensaje, en el problema no se hace mención ah que el numero de caracteres en el mensaje los cuenta después del fallo, ahí asumí que el numero de caracteres del mensaje es un valor para segurar la integridad del mensaje

**Comment by fakereto** [comment]
Correcto, queda de 22 despues de limpar, pero se valida la entrada 38 caracteres.
Nota: Ninguna instrucción en el libro de instrucciones contiene dos letras iguales seguidas): Son las instrucciones no los mensajes

**Comment by OscarRicoB** [comment]
**Solucionado con el commit https://github.com/OscarRicoB/P1-encrypted-message-Python/commit/adc6618e4248ef2e0be73d8b9fc21b74c0174795**
Respecto al primer error que tuviste con el archivo de entrada en ruta relativa, en mi entorno no tuve ningún problema usando rutas relativas, ni la necesidad de encerrarlas en cadenas "../../casos/P1-CP1-OK-SN.txt" como siguieres fue necesario. _que versión del interprete estas utilizando, yo **3.8.1**_
